package com.philia093.neofactory.util;

/**
 * Central place for every magic number used by the game.
 * <p>
 * One block covers {@link #TILE_SIZE} world units, which is also the pixel size
 * of a block texture. Terrain and entity logic therefore works with block
 * coordinates and converts them into world units when needed, while the renderer
 * places a tile at {@code blockX * TILE_SIZE}.
 */
public final class Constants {

    /** Application / window title. */
    public static final String WINDOW_NAME = "NeoFactory";

    /** Size of a single block in world units, equal to the texture size in pixels. */
    public static final int TILE_SIZE = 16;

    /** Side length in blocks of a single square chunk. */
    public static final int CHUNK_SIZE = 16;

    /**
     * Index of the floor layer inside a chunk.
     * <p>
     * The floor is the ground the player walks on, for example grass, sand or
     * stone. It is generated by the biome driven terrain generator.
     */
    public static final int LAYER_FLOOR = 0;

    /**
     * Index of the object layer inside a chunk.
     * <p>
     * This is the layer the player stands in. It holds trees, plants and
     * everything the player places later on; an empty object layer cell is
     * walkable.
     */
    public static final int LAYER_OBJECT = 1;

    /**
     * Player walking speed in blocks per second at zoom level one.
     * <p>
     * The movement code multiplies this value by {@link #TILE_SIZE} to get world
     * units and by the current camera zoom, so the player keeps feeling equally
     * fast no matter how far the camera is zoomed out.
     */
    public static final float PLAYER_SPEED = 12.0f;

    /** Side length of the square player collision box in blocks. */
    public static final float PLAYER_HITBOX = 0.7f;

    /**
     * Visual scale of the player marker. The marker is an 8 by 8 pixel icon,
     * a scale of two makes it fill a single block tile.
     */
    public static final float PLAYER_ICON_SCALE = 2.0f;

    /** Amount of blocks visible on the shorter screen axis at zoom level one. */
    public static final float VIEW_BLOCKS = 32.0f;

    /** Smallest camera zoom, the closest view, a block appears twice as large. */
    public static final float ZOOM_MIN = 0.5f;

    /** Largest camera zoom, the most distant view, a block shrinks to a third. */
    public static final float ZOOM_MAX = 3.0f;

    /** Cell size in pixels of a single item icon. */
    public static final int ITEM_ICON_SIZE = 16;

    /** Multiplicative zoom step applied per mouse wheel notch. */
    public static final float ZOOM_STEP = 1.1f;

    /** Number of chunks generated around the spawn position at world creation. */
    public static final int SPAWN_CHUNK_RADIUS = 2;

    /** Cell index inside {@code map/map_icons.png} used as the player marker. */
    public static final int MAP_ICON_PLAYER = 0;

    /** Side length in pixels of a single cell inside {@code map/map_icons.png}. */
    public static final int MAP_ICON_CELL_SIZE = 8;

    /** Color used to clear the frame before the world is drawn. */
    public static final float SKY_RED = 0.42f;
    public static final float SKY_GREEN = 0.62f;
    public static final float SKY_BLUE = 0.92f;

    private Constants() {
        // Utility class: never instantiated.
    }
}
